default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  pool: 5

development:
  <<: *default
  database: socify_development

test:
  <<: *default
  database: socify_test

production:
  <<: *default
  database: socify_production
  username: socify
  password: <%= ENV["SOCIFY_DATABASE_PASSWORD"] %>
